const mongoose = require("mongoose")

const PostSchema = new mongoose.Schema({
    title:{
        type:String,
        required:true,
        unique:true
    },
    desc:{
        type:String,
        required:true
    },
    photo:{
        type:String,
        required:false,
    },
    username:{
        type:String,
        required:true,
    },
    author:{
        type:String,
        required:true,
    },
    authorRoll:{
        type:String,
        default:""
    },
    authorPhoto:{
        type:String,
        default:""
    },
    authorBatch:{
        type:String,
        default:""
    },
    authorDepartment:{
        type:String,
        default:""
    },
    authorEmail:{
        type:String,
        required:true,
    },
    authorFbLink:{
        type:String,
        default:""
    },
    authorTwitterLink:{
        type:String,
        default:""
    },
    authorLinkedinLink:{
        type:String,
        default:""
    },
    categories:{
        type:Array,
        default:""
    }
},
{timestamps:true}
);

module.exports = mongoose.model("Post",PostSchema);